import type {Metadata}
from 'next'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata : Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({children} : {
    children: React.ReactNode
}) {
    return (
        <section className="flex items-center justify-center min-h-screen bg-[#111113] w-full p-4">
            {children}
        </section>
    )
}